### ISSUE TITLE
Begin Semantic Versioning

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#10]
## Issue Overview

The versions referenced throughout the plugin are currently `1.0.0` but that version should be reserved for public release. Let's set the current version to `0.1.0` so that we can create milestones based off a version that makes sense.

Going forward, follow http://semver.org/ when updating patches, minor, and major versions.

## Tasks
- [x] Find all instances of `1.0.0` and replace with `0.1.0`
- [x] Confirm change in plugin header.
- [x] Confirm change in `@since` tags.

**Comment by kevinwhoffman** [comment]
Plugin version has been set to `0.1.0` across the entire plugin.
