### ISSUE TITLE
feat(collection): use CSS Grid to display reviews gallery

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#103]
## User Story

As a developer, I want to display reviews via CSS Grid instead of Flexbox so that my galleries can respond to the available space.

## Current Behavior

I currently use Flexbox and have to specifically choose the max number of columns rather than allowing the gallery to determine its own best fit. My layout options are also limited as Flexbox excels at one-directional layouts whereas Grid excels at two-directional layouts.

## Expected Behavior

I expect to use CSS Grid as it is the future of grid-style layouts on the web and should be introduced early before third-party developers start customizing styles based on another approach.

## Possible Solution

Replace the current Flexbox gallery layout with CSS Grid and add a `Best Fit` option to the `Max Columns` control.

## Related

- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
- https://www.youtube.com/watch?v=FEnRpy9Xfes
- https://www.youtube.com/watch?v=dQHtT47eH0M

## Tasks

- [x] Replace Flexbox with CSS Grid for the reviews gallery layout.
- [x] Add `Best Fit` option to `Max Columns` control.
- [x] Add fallback styles for browsers that don't support Grid.
