### ISSUE TITLE
Add Yelp search support for multiple businesses in Reviews Builder

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#11]
## Issue Overview

The existing Yelp widget has two presentation formats:

- Single business with reviews.
- Multiple businesses with ratings based on a search query in a location.

We should add support for the multi-business option for customers transitioning to WPBR.

## Screenshot

**Single Business (existing functionality)**
![image](https://user-images.githubusercontent.com/1938671/32805787-7e06058e-c958-11e7-970d-86d9df03835e.png)

**Multiple Businesses (proposed functionality)**
![image](https://user-images.githubusercontent.com/1938671/32805230-d2585a9e-c956-11e7-8520-0c9507c2a933.png)

## Tasks

- [ ] Add option to select `Single Business` or `Multiple Businesses` when `Yelp` is selected.
- [ ] Write PHP request that uses the [`/businesses/search`](https://www.yelp.com/developers/documentation/v3/business_search) endpoint.
- [ ] Write AJAX function to call the request method from the Reviews Builder.

**Comment by kevinwhoffman** [comment]
Note this will require special handling since it is the only format not based on reviews of a single business. I recommend saving the search query from the Reviews Builder but caching the results in a transient similar to the existing Yelp plugin.
