### ISSUE TITLE
Complete business search functionality in Reviews Builder

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#12]
## Issue Overview

The Reviews Builder needs to detect the currently selected platform in order to search the appropriate platform for businesses. Upon clicking `Search`, a remote request is triggered that searches the selected platform for a business matching the search query.

## Screenshots

![image](https://user-images.githubusercontent.com/1938671/32810508-351c4016-c969-11e7-8cb5-c097f7fb9bbc.png)

## Tasks

- [x] Write Google business request
- [x] Write Facebook business request
- [x] Write Yelp business request
- [x] Write YP business request
- [x] Write JavaScript method to call these requests via AJAX.
