### ISSUE TITLE
Add Pro Features page

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#16]
## Issue Overview

The Pro Features page exists in the free version of the plugin and communicates features available in the Pro version. It requires copy and ideally includes images representing each feature.

**Pro Features include:**

- Display Review Mash-ups
- Add Custom Reviews
- Filter Negative Reviews
- Get More Presentation Styles
- Customize Order of Reviews
- Access Priority Support

## Tasks

- [x] Define the Pro Features to be listed on this page.
- [ ] Write copy (1 heading + 1 paragraph for each feature).
- [ ] Create graphics to represent each feature.
- [ ] Write PHP method to retrieve the page from remote server.
- [ ] Create the view that exists on the remote server (Note: Use existing `wpbr-gallery` class within the plugin).

**Comment by kevinwhoffman** [comment]
@DevinWalker @mathetos I had previous placed this in a `Pro Features` tab on the Settings page, but I think it would get more attention as its own page in the plugin menu, similar to the `Premium` page in Yoast.

![image](https://user-images.githubusercontent.com/1938671/32811926-5da17e1e-c970-11e7-9103-53f9626f8923.png)

Users may not return to the settings screen very often after the initial setup, so having it in the admin menu would make it more visible while still not being too disruptive. What do you think?

**Comment by mathetos** [comment]
I agree, just like Give has "Add-ons" as a sub-menu.

**Comment by kevinwhoffman** [comment]
Closing due to strict focus on Pro plugin.
