### ISSUE TITLE
feat(collection): add carousel format

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#18]
## Issue Overview

Complete the integration of [slick](http://kenwheeler.github.io/slick/) as the carousel solution.

## Tasks

- [x] Enqueue slick assets.
- [ ] Add custom plugin styles to work with WPBR themes.
- [ ] Debug flexbox issue that was breaking the slider when placed within a flex container.

**Comment by DevinWalker** [comment]
Is the flexbox item a big deal? Can we push that until post-launch?

**Comment by kevinwhoffman** [comment]
It's important insofar as the container that displays the preview in the Reviews Builder is a flex container. I will look into it briefly and report back if I think it's a blocker.
