### ISSUE TITLE
Update tab functionality to work with config-based Settings UI

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#33]
## Issue Overview

Some changes in markup resulted from the switch to a config-based UI. That means the JS needs updated to work with the new markup.

## Tasks

- [x] Update [`admin-tabs.js`](https://github.com/WordImpress/WP-Business-Reviews/blob/develop/assets/src/js/admin-tabs.js) to work with the new markup.
- [x] Fix styles using wrapper class to modify the existing `wpbr-field` class.
- [x] Ensure that the active tab and active section are maintained when reloading.

**Comment by kevinwhoffman** [comment]
Admin tabs should be fully functional with all field types display correctly based off the `config-settings.php`.
