### ISSUE TITLE
Split Facebook Pages into two fields

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#43]
## Issue Overview

The Facebook Pages field requires unique behavior separate from all other fields. It should really be two fields in order to work with the config-based approach.

- `facebook_user_token` - internal field that stores the long-lived token
- `facebook_pages` - stores the pages that the user has access to

## Tasks

- [x] Split field into two separate fields described above.
- [x] Save pages and token to separate fields.
- [x] Load pages on Settings page if they exist in database.
