### ISSUE TITLE
Research how the plugin can benefit from a Postman Collection

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#45]
## Issue Overview

A [Postman Collection](https://www.getpostman.com/docs/postman/collections/creating_collections) lets you group individual requests together. You can organize these requests in folders.

WPBR relies on several review platforms with APIs that are prone to change. It will be helpful to have these API requests in a Collection for internal testing and project documentation.

## Tasks

- [ ] Look at other examples of projects that version control Postman Collection (@DevinWalker  mentioned Authorize.net)
- [ ] Determine whether Pro accounts are needed for this functionality.
- [ ] Discuss with @mathetos how this fits into overall docs.
- [ ] Research [Postman Monitors](https://www.getpostman.com/docs/postman/monitors/intro_monitors) for testing.
- [ ] Discuss with Devin/Ravinder how Postman testing fits in with PHP unit testing.

**Comment by mathetos** [comment]
I do want to have a section for "Developer Docs" that will be like developer tutorials. Things like "How to Register a Custom Platform", or "How to Query and filter Reviews". This would go really well into that section. At this point that section won't be started until after launch though.
