### ISSUE TITLE
Improve the redirect UX when authenticating Facebook

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#49]
## Issue Overview

The current Facebook authentication is functionally complete, however the UX could be improved when the user returns to wordimpress.com and is immediately redirected.

## Tasks

- [x] Style the redirect page on wpbusinessreviews.com
- [x] Add a 3-second delay so the flash is not jarring.
- [x] Ensure the Facebook status icon shows green check upon return.

## Related

https://github.com/WordImpress/wp-business-reviews/issues/90

**Comment by DevinWalker** [comment]
This has been resolved. I've added the following styling to the page:

![2018-05-08_12-51-39](https://user-images.githubusercontent.com/1571635/39780383-ef3349d2-52c0-11e8-8743-9130732e7ffa.png)

I also added a 3-second delay for the redirect.
