### ISSUE TITLE
Render Settings UI using config-based approach as seen in Reviews Builder

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#5]
## Issue Overview

The Reviews Builder fields are based on a config file that can easily be filtered or extended. We should carry over the same approach to the Settings UI so that it can share the same field logic and views.

## Tasks
- [x] Update Settings config to use the same structure as Reviews Builder config
- [x] Add `process_config` method to `Settings_UI` to convert config to `Field` objects.
- [x] Update view to work with the new `Field` objects.
