### ISSUE TITLE
Create Platform_Manager class

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#52]
## Issue Overview

There is a shared need throughout the plugin to identify:

- Existing platforms (free + pro)
- Active platforms (ones the user has marked active)
- Connected platforms (ones with a verified connection to the remote API)

This `Platform_Manager` class can serve both `Settings` and `Reviews_Builder` classes and provide a single point of entry for registering new platforms down the road.

This functionality already exists in the `Settings` class, but it should be migrated to `Platform_Manager` class for reuse.

## Tasks

- [x] Create `get_platforms()` method
- [x] Create `get_active_platforms()` method
- [x] Create `get_connected_platforms()` method
- [x] Add filter to the platforms in `settings-config.php` so this class can filter those platforms.

**Comment by kevinwhoffman** [comment]
Resolved in #53.
