### ISSUE TITLE
Add Reviews Builder launcher

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#54]
## Issue Overview

The challenge described in #14 regarding the need for different controls per platform is difficult to solve once the builder UI has loaded. It would require a lot of conditional JS to show/hide the appropriate controls per platform.

The challenge is simplified if we have the user select a platform _before_ entering the builder UI. Platform selection could be accomplished through a launcher like the one below.

**Two possible flows could result:**

- User selects one of four platforms to build a new review set.
- User selects an existing review set that they built in a previous session.

## Concept

![wpbr-mockup-builder-selection-v01](https://user-images.githubusercontent.com/1938671/34065801-fe2429a6-e1d3-11e7-9a1a-60222a80b328.png)

## Separate Configs for Each Platform

- Currently there is one config that contains field definitions for all platforms, but not all controls apply to each platform. By having the user choose a platform up front, we can load a config that is specific to that platform.

### Mash-ups

In the Pro version, a fifth Mash-up option would be available.

## Query Parameters

- `wpbr_platform=google_places` - determines which platform config to load
- `wpbr_review_set=123` - determines which review set to prepopulate

## Tasks

- [x] Discuss user flow for new Review Sets.
- [x] Add the new launcher page.
- [x] Style new launcher page.
- [x] Update reviews builder to interpret the query params.

**Comment by DevinWalker** [comment]
Nice job on this one 👍
