### ISSUE TITLE
Update save methods to work with config-based Settings UI

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#6]
## Issue Overview

After the Settings UI is transitioned to the config-based approach described in #5, the save methods will need updated.

## Tasks

- [x] Structure both Reviews Builder and Settings config to match.
- [x] Write method to parse fields from `Config` object.
- [x] Ensure all fields are correctly saved to options prefixed by `wp_business_reviews_`.
- [x] Ensure all saved fields are correctly populated when viewing the Settings UI.
