### ISSUE TITLE
Normalize all timestamps to Unix time

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#68]
## Issue Overview

Each platform returns timestamps in a different format. Let's normalize them to Unix time using [`strtotime()`](http://php.net/manual/en/function.strtotime.php). That way we have a common starting point that can be formatted consistently.

## Tasks
- [x] Save timestamps in Unix time.
- [x] Display timestamps in consistent format using [date-fns](https://date-fns.org/).
- [ ] Display platform name next to timestamp.
