### ISSUE TITLE
Reflect connection status in Platform Status field

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/WP-Business-Reviews#7]
## Issue Overview

Each platform has a field called `Platform Status` in the Settings screen that should reflect whether that platform is currently connected or not.

## Tasks
- [x] Add method to `Platform_Status_Field` class to read connected platforms from database.
- [x] Reflect `Connected` or `Disconnected` in the field.
- [x] Also reflect status through red or green icon in sidebar menu.

**Comment by DevinWalker** [comment]
@kevinwhoffman does it need an entire class to simply display a status? Seems like it could just be a function.

**Comment by kevinwhoffman** [comment]
There is already a base `Field` class that every field uses. This would just extend that class and add a method to check the platform status.

**Comment by kevinwhoffman** [comment]
Below are the various requests necessary, split amongst the settings screen and reviews builder. These requests are being migrated from Postman into factory classes.

```
google_places

- settings screenj: test request
- reviews builder: business search
- reviews builder: place details, including reviews

facebook

- settings screen: test request
- settings screen: oauth request that stores page tokens in hidden field
- reviews builder: page details request
- reviews builder: page ratings request

yelp

- settings screen: test request
- settings screen: use client ID and client secret to get OAuth token, then store OAuth token in own field
- reviews builder: yelp fusion business search
- reviews builder: yelp fusion reviews

yp

- settings screen: test request
- reviews builder: business search
- reviews builder: yp reviews

wp.org

- settings screen: test request
- reviews builder: plugin search
```
