### ISSUE TITLE
Add `Review_Source` PHP class

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#85]
## Issue Overview

In order to save and retrieve Review Sources and pass them to the front end as a JS object, there should be a `Review_Source` class. This class will house Review Source details as properties and contain methods for retrieving them.

## Tasks

- [x] Add `Review_Source` class.
- [x] Update the normalizer classes to return `Review_Source` objects.
- [x] Add `Review_Source_Deserializer` to retrieve the `Review_Source` object from database.
