### ISSUE TITLE
feat(builder): load existing Review Collection

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/wp-business-reviews#86]
## Issue Overview

Users should be able to load a Review Collection created during a previous session and continue editing.

## Tasks

- [x] Add a Builder Table for selecting an existing review collection.
- [x] Allow user to load an existing collection and continue editing.
- [x] Redirect user back to the collection they just saved.
- [x] Break out Builder into component classes to separate concerns.
